database:
  driver: postgres
  name: users
  host: postgres
  password: password
  port: 5432
  user: postgres
  maxconns: 10
  idleconns: 10

urlhost: localhost
urlport: 80

# "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"